### ISSUE TITLE
Is it possible to set percentages with variables?

### ISSUE THREAD

**Issue by elchamaa** [Keyframes/Keyframes#12]
Hey, thank you so much for this library.

I was wondering if it was possible to set the keyframe percentages through a variable hence making it dynamic. When I tried to use a string variable that looks like so '50%', it doesn't seem that it worked.

Cheers

**Comment by krazyjakee** [comment]
@elchamaa percentage of what? Can you please provide an example?

**Comment by elchamaa** [comment]
Yup, something like the below where the keyframe percentages are decided based on how a variable calculates.

```
Keyframes.define([{
    name: 'heartbeat3',
    '0%': {transform: 'translateZ(0) scale(1.5)'},
    firstPercentage: {transform: 'translateZ(0) scale(3) rotate(0deg)'},
    secondPercentage: {transform: 'translateZ(0) scale(3) rotate(360deg)'},
    thirdPercentage: {transform: 'translateZ(0) scale(1.5) rotate(360deg)'},
    fourthPercentage: {transform: 'translateZ(0) scale(1.5) rotate(360deg)'}
}])
```

**Comment by krazyjakee** [comment]
Try the es6 solution https://stackoverflow.com/q/11508463/1013097
